version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-app
        working_dir: /var/www
        volumes:
            - ./:/var/www
        depends_on:
            - mysql
        networks:
            - laravel

    nginx:
        image: nginx:alpine
        container_name: laravel-nginx
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel

    mysql:
        image: mysql:8.0
        container_name: laravel-mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: podcast_db
            MYSQL_ROOT_PASSWORD: your_password_here
            MYSQL_USER: root
            MYSQL_PASSWORD: your_password_here
        ports:
            - "3306:3306"
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - laravel

    redis:
        image: redis:alpine
        container_name: laravel-redis
        ports:
            - "6379:6379"
        networks:
            - laravel

volumes:
    mysql-data:

networks:
    laravel:
        driver: bridge
